config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'


  resources :charges

  get '/user/new', to: 'user#new', as: "subscribe"
  post 'user/new', to: 'user#create'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create
    @user = User.new(name: params[:session]["name"], email: params[:session]["email"])
    puts params
    @user.save
    NewsletterMailer.new.send
    flash.now[:danger] = "Tu as bien été enregistré.e !"

    redirect_to '/'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/charges/create.html.erb
<h2>Merci à toi ! Tu as payé <strong>$ 5.00</strong> !</h2>
<p>Clique <a href="/user/new">ici</a> pour pourvoir t'inscrire !</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>

</head>

<body>

<h1>Bienvenue à toi !</h1>
<p>Sur ce site, tu peux t'inscrire pour recevoir une super newsletter ! Il te suffit de cliquer sur le lien ci-dessous pour accéder au lien de paiement !</p>
<a href="/charges/new">Je paye 5 dollars et je m'abonne à la super newsletter !</a>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeNewsletter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/user/new.html.erb
<h1>Inscris-toi à la super Newsletter !</h1>
<% provide(:title, "Inscription à la Newsletter") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: subscribe_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %></br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %></br>

      <%= f.submit "M'inscrire", class: "btn btn-primary" %>
    <% end %></br>

  </div>

</div>